name: Consumer Test

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  test-consumer-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js & Yarn v1
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable && corepack prepare yarn@1.22.22 --activate

      - name: Build package
        run: yarn install --frozen-lockfile && yarn build

      - name: Pack tarball
        run: yarn pack --filename geo-bounds-utility.tgz

      - name: Test install in consumer environments
        run: |
          # Node.js (backend) test
          mkdir consumer-node && cd consumer-node
          yarn init -y
          yarn add ../geo-bounds-utility.tgz
          yarn add -D typescript @types/node
          echo "import { calculateBoundingCoordinates } from 'geo-bounds-utility';" > test.ts
          echo "const bounds = calculateBoundingCoordinates({ lat: 1, lng: 1, radiusKm: 1 });" >> test.ts
          echo "console.log(bounds.minLat);" >> test.ts
          npx tsc test.ts --noEmit
          cd ..

          # Frontend (browser) test
          mkdir consumer-web && cd consumer-web
          yarn init -y
          yarn add ../geo-bounds-utility.tgz
          yarn add -D typescript
          echo "import { calculateBoundingCoordinates } from 'geo-bounds-utility';" > test.ts
          echo "const bounds = calculateBoundingCoordinates({ lat: 1, lng: 1, radiusKm: 1 });" >> test.ts
          echo "console.log(bounds.minLat);" >> test.ts
          npx tsc test.ts --noEmit
          cd ..

          # ts-node consumer test
          mkdir consumer-ts-node && cd consumer-ts-node
          yarn init -y
          yarn add ../geo-bounds-utility.tgz
          yarn add -D typescript ts-node @types/node
          echo "import { calculateBoundingCoordinates } from 'geo-bounds-utility';" > test.ts
          echo "console.log(calculateBoundingCoordinates({ lat: 1, lng: 1, radiusKm: 1 }));" >> test.ts
          npx ts-node test.ts
          cd ..

          # ESM consumer test
          mkdir consumer-esm && cd consumer-esm
          yarn init -y
          yarn add ../geo-bounds-utility.tgz
          yarn add -D typescript
          echo '{ "type": "module" }' > package.json
          echo 'import { calculateBoundingCoordinates } from "geo-bounds-utility";' > test.mts
          echo 'const bounds = calculateBoundingCoordinates({ lat: 1, lng: 1, radiusKm: 1 });' >> test.mts
          echo 'console.log(bounds.minLat);' >> test.mts
          echo '{
            "compilerOptions": {
              "target": "ES2022",
              "module": "ESNext",
              "moduleResolution": "node",
              "strict": true,
              "esModuleInterop": true,
              "types": []
            }
          }' > tsconfig.json
          npx tsc test.mts --noEmit
          node test.mts
